CREATE TABLE ALUMNOS_NOTAS_J (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100),
    NOTA1 NUMBER(5,2),
    NOTA2 NUMBER(5,2),
    NOTA3 NUMBER(5,2),
    NOTA4 NUMBER(5,2),
    NOTA5 NUMBER(5,2),
    SUMA NUMBER(8,2),
    PROMEDIO NUMBER(8,2),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_ALUMNOS_J PRIMARY KEY(ID)
);

COMMIT;